---
- name: Install stack
  become: True
  apt:
    name: "{{ item }}"
  with_items:
    - "haskell-stack"
    - "g++"
    - "gcc"
    - "git"
    - "gnupg"
    - "libc6-dev"
    - "libffi-dev"
    - "libgmp-dev"
    - "make"
    - "xz-utils"
    - "zlib1g-dev"
  tags:
    - install

- name: Install a global GHC
  command: "stack setup --install-ghc"
  args:
    chdir: "{{ home }}"
  tags:
    - longrun
