---
- name: Symlink the proselint configuration
  file:
    src: "{{ dotfiles}}/dotfiles/proselint/proselintrc"
    dest: "{{ home }}/.proselintrc"
    state: link
    force: True

- name: Install proselint
  pip:
    name: proselint
    extra_args: "--user"
    executable: pip3
  tags:
    - install
