---
- name: "Symlink the proselint configuration"
  file:
    src: "proselintrc"
    dest: "{{ home }}/.proselintrc"
    state: "link"
    force: True
    owner: "{{ ansible_user }}"

- name: "Install proselint"
  pip:
    name: "proselint"
    extra_args: "--user"
    executable: "pip3"
