sudo: required

language: generic

before_install:
  - |
    curl -L http://bootstrap.saltstack.org | sudo sh -s -- git develop
    sudo mkdir -p /srv/salt/states
    sudo cp -r states/* /srv/salt/states
    sudo cp .travis/minion /etc/salt/minion
    sudo service salt-minion restart

install:
  - docker build -t lwm/dotfiles .

script:
  - sudo salt-call --local --retcode-passthrough dockerng.highstate lwm/dotfiles

notifications:
  email: false
