sudo: required

language: python

before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- git develop

install:
  - sudo mkdir -p /srv/salt/states
  - sudo cp -r states/* /srv/salt/states
  - sudo cp .travis/minion /etc/salt/minion
  - sudo service salt-minion restart

script:
  - sudo salt-call state.show_highstate --local --retcode-passthrough
