---
- name: Install neovim
  apt:
    name: neovim

- name: Make sure the neovim configuration folder is created
  file:
    path: "{{ nvim }}"
    state: directory
    mode: 0755

- name: Symlink neovim configuration
  file:
    src: "{{ dotfiles }}/dofiles/nvim/init.vim"
    dest: "{{ nvim }}/init.vim"
    state: link

- name: Install neovim plugin manager
  command: "curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

- name: Install neovim plugins
  command: "vim +PlugInstall +qall"
