---
- name: Install stack
  become: True
  apt:
    name: "{{ item }}"
  with_items:
    - "haskell-stack"
    - "g++"
    - "gcc"
    - "git"
    - "gnupg"
    - "libc6-dev"
    - "libffi-dev"
    - "libgmp-dev"
    - "make"
    - "xz-utils"
    - "zlib1g-dev"
  tags:
    - install

- name: Install a global GHC
  command: "stack setup --install-ghc"
  args:
    chdir: "{{ home }}"
  tags:
    - longrun

- name: Upgrade stack
  command: "stack upgrade"
  args:
    chdir: "{{ home }}"
  tags:
    - longrun

- name: Make sure the stack configuration folder is created
  file:
    path: "{{ home }}/.stack"
    state: directory
    mode: 0755

- name: Symlink the stack configuration
  file:
    src: "{{ dotfiles }}/dotfiles/stack/config.yaml"
    dest: "{{ home }}/.stack/config.yaml"
    force: True
