---
- name: Install stack
  apt:
    name: haskell-stack

- name: Install a global GHC
  command: "stack setup --install-ghc"
  args:
    chdir: "{{ home }}"

- name: Upgrade stack
  command: "stack upgrade --git"

- name: Symlink the stack configuration
  file:
    src: "{{ dotfiles }}/dotfiles/stack/config.yaml"
    dest: "{{ home }}/.stack/config.yaml"
