---
- name: Install ctags
  become: True
  apt:
    name: exuberant-ctags

- name: Symlink exuberant-ctags configuration
  file:
    src: "{{ dotfiles }}/dotfiles/exuberant-ctags/ctags"
    dest: "{{ lookup('env', 'HOME') }}/.ctags"
    state: link
    force: True
    owner: "{{ ansible_user }}"
