---
- name: Symlink the mailcap configuration
  file:
    src: "{{ dotfiles }}/dotfiles/mailcap/mailcap"
    dest: "{{ home }}/.mailcap"
    state: link
    force: True
    owner: "{{ ansible_user }}"
