---
- name: Install Git
  apt:
    name: git
  tags:
    - install

- name: Clone the dotfiles repository
  git:
    repo: "https://github.com/lwm/dotfiles.git"
    dest: "{{ dotfiles }}"

- name: Delete the existing HTTPS remote URL
  command: "git remote rm origin"
  args:
    chdir: "{{ dotfiles }}"

- name: Set a new SSH style remote URL
  command: "git remote add origin git@github.com:lwm/dotfiles.git"
  args:
    chdir: "{{ dotfiles }}"
