---
- name: Install tmux
  apt:
    name: tmux
  tags:
    - install

- name: Symlink the tmux configuration
  file:
    src: "{{ dotfiles }}/dotfiles/tmux/tmux.conf"
    dest: "{{ home }}/.tmux.conf"
    state: link
