---
- name: "Install Git"
  become: True
  apt:
    name: "git"

- name: "Symlink the Git configuration"
  file:
    src: "gitconfig"
    dest: "{{ home }}/.gitconfig"
    state: "link"
    force: True
    owner: "{{ ansible_user }}"

- name: "Symlink the Git ignore configuration"
  file:
    src: "gitignore_global"
    dest: "{{ home }}/.gitignore_global"
    state: "link"
    force: True
    owner: "{{ ansible_user }}"
