---
- name: Install tmux
  become: True
  apt:
    name: tmux

- name: Symlink the tmux configuration
  file:
    src: "{{ dotfiles }}/dotfiles/tmux/tmux.conf"
    dest: "{{ home }}/.tmux.conf"
    state: link
    force: True
    owner: "{{ ansible_user }}"
