---
- name: Install msmtp
  apt:
    name: msmtp
  tags:
    - install

- name: Symlink the msmtp configuration
  file:
    src: "{{ dotfiles }}/dotfiles/msmtp/msmtprc"
    dest: "{{ home }}/.msmtprc"
    state: link
    force: True
