---
- name: Install ctags
  apt:
    name: exuberant-ctags
  tags:
    - install

- name: Symlink exuberant-ctags configuration
  file:
    src: "{{ dotfiles }}/dotfiles/exuberant-ctags/ctags"
    dest: "{{ lookup('env', 'HOME') }}/.ctags"
    state: link
    force: True
