---
- name: Install IPython
  become: True
  apt:
    name: ipython3

- name: Make sure the ipython configuration folder is created
  file:
    path: "{{ home }}/.ipython"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"

- name: Symlink the ipython configuration
  file:
    src: "{{ dotfiles }}/dotfiles/ipython/profile_default"
    dest: "{{ home }}/.ipython/profile_default"
    state: link
    force: True
    owner: "{{ ansible_user }}"
